version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: crawler-rabbit
    ports:
      - "5673:5672"    # host 5673 -> container 5672 (AMQP)
      - "15673:15672"  # host 15673 -> container 15672 (UI)
  redis:
    image: redis:7-alpine
    container_name: crawler-redis
    ports:
      - "6380:6379"    # host 6380 -> container 6379 (Redis)