# =========================
# RABBITMQ
# =========================
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5673
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# =========================
# REDIS
# =========================
spring.data.redis.host=localhost
spring.data.redis.port=6380
#spring.data.redis.password=

# log level for AMQP
logging.level.org.springframework.amqp=INFO

spring.application.name=spring-again-t2404e
spring.datasource.url=jdbc:mysql://localhost:3306/vietnamnet
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

# =========================
# CRAWLER NETWORK PROFILE
# =========================

# LinkCrawlerBot role
crawler.link.enabled=true

# ContentCrawlerBot role
crawler.content.enabled=true

# ???ng d?n t?i file txt ch?a User-Agent (m?i dòng 1 UA, dòng # là comment)
crawler.network.user-agent-file=./config/user-agents.txt

# File txt ch?a fake IP (m?i dòng 1 IPv4), n?u không có s? random IP
crawler.network.ip-file=./config/fake-ips.txt

# File txt ch?a proxy: host:port ho?c host:port:username:password (m?i dòng 1 proxy)
crawler.network.proxy-file=./config/proxies.txt

app.jwt.secret=quy-sieu-bi-mat-cua-ban-nen-dai-hon-32-ki-tu-123456
app.jwt.expiration-ms=3600000
