# =========================
# RABBITMQ
# =========================
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5673
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
# (không c?n virtual-host n?u dùng m?c ??nh)

# =========================
# REDIS
# =========================
spring.data.redis.host=localhost
spring.data.redis.port=6380
# spring.data.redis.password=   # n?u Redis không ??t password thì ?? tr?ng ho?c b? dòng này

# (tu? ch?n) log nh? cho AMQP
logging.level.org.springframework.amqp=INFO

spring.application.name=spring-again-t2404e
spring.datasource.url=jdbc:mysql://localhost:3306/vietnamnet
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
